// <auto-generated />
using System;
using Api_ZooManagement_SWP391.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_ZooManagement_SWP391.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Account", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Animal", b =>
                {
                    b.Property<string>("AnimalID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthCheck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.Property<string>("SpeciesAnimalSpeciesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AnimalID");

                    b.HasIndex("SpeciesAnimalSpeciesId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.AnimalCage", b =>
                {
                    b.Property<string>("AnimalId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CageId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AnimalId", "CageId");

                    b.HasIndex("CageId");

                    b.ToTable("AnimalCages");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.AnimalTrainer", b =>
                {
                    b.Property<string>("AnimalId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrainerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AnimalId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("AnimalTrainers");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Area", b =>
                {
                    b.Property<string>("AreaId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AreaId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Cage", b =>
                {
                    b.Property<string>("CId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("AnimalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("AreaID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("CId");

                    b.HasIndex("AreaID");

                    b.ToTable("Cages");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.FeedSchedule", b =>
                {
                    b.Property<string>("AnimalID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FoodId")
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AnimalID", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("FeedSchedules");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Food", b =>
                {
                    b.Property<string>("FoodId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodCategoryCategoryId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.HasIndex("FoodCategoryCategoryId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.FoodCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("FoodCategories");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Guest", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("GuestEmail");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TicketId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.SpeciesAnimal", b =>
                {
                    b.Property<string>("SpeciesId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeciesId");

                    b.ToTable("speciesAnimals");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Staff", b =>
                {
                    b.Property<string>("SId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("SId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TicketId");

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.TrainerExperience", b =>
                {
                    b.Property<string>("TrainerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WorkType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TrainerId", "WorkType");

                    b.HasIndex("WorkType");

                    b.ToTable("TrainerExperiences");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.WorkExperience", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.ZooTrainer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.Property<string>("StaffSId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StaffSId");

                    b.ToTable("ZooTrainers");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Admin", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("Api_ZooManagement_SWP391.Entities.Admin", "Email")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Animal", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.SpeciesAnimal", "SpeciesAnimal")
                        .WithMany()
                        .HasForeignKey("SpeciesAnimalSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeciesAnimal");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.AnimalCage", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Animal", "Animal")
                        .WithMany("AnimalCages")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.Cage", "Cage")
                        .WithMany("AnimalCages")
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.AnimalTrainer", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Animal", "Animal")
                        .WithMany("AnimalTrainers")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.ZooTrainer", "ZooTrainer")
                        .WithMany("AnimalTrainers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("ZooTrainer");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Area", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Staff", "Staff")
                        .WithOne("Area")
                        .HasForeignKey("Api_ZooManagement_SWP391.Entities.Area", "AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Cage", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Area", "Area")
                        .WithMany("Cages")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.FeedSchedule", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Animal", "Animal")
                        .WithMany("FeedSchedules")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.Food", "Food")
                        .WithMany("FeedSchedules")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Food", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.FoodCategory", null)
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryCategoryId");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Order", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Guest", "Guest")
                        .WithMany("Orders")
                        .HasForeignKey("GuestEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.OrderDetail", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.Ticket", "Ticket")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Staff", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("Api_ZooManagement_SWP391.Entities.Staff", "Email")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.TrainerExperience", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.ZooTrainer", "ZooTrainer")
                        .WithMany("TrainerExperiences")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.WorkExperience", "WorkExperience")
                        .WithMany("TrainerExperiences")
                        .HasForeignKey("WorkType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkExperience");

                    b.Navigation("ZooTrainer");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.ZooTrainer", b =>
                {
                    b.HasOne("Api_ZooManagement_SWP391.Entities.Account", "Account")
                        .WithOne("ZooTrainer")
                        .HasForeignKey("Api_ZooManagement_SWP391.Entities.ZooTrainer", "Email")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Api_ZooManagement_SWP391.Entities.Staff", "Staff")
                        .WithMany("ZooTrainers")
                        .HasForeignKey("StaffSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Account", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Staff")
                        .IsRequired();

                    b.Navigation("ZooTrainer")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Animal", b =>
                {
                    b.Navigation("AnimalCages");

                    b.Navigation("AnimalTrainers");

                    b.Navigation("FeedSchedules");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Area", b =>
                {
                    b.Navigation("Cages");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Cage", b =>
                {
                    b.Navigation("AnimalCages");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Food", b =>
                {
                    b.Navigation("FeedSchedules");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Guest", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Staff", b =>
                {
                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("ZooTrainers");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.Ticket", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.WorkExperience", b =>
                {
                    b.Navigation("TrainerExperiences");
                });

            modelBuilder.Entity("Api_ZooManagement_SWP391.Entities.ZooTrainer", b =>
                {
                    b.Navigation("AnimalTrainers");

                    b.Navigation("TrainerExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
